<Project>
  <PropertyGroup>
    <!-- Enable central package management, https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="CliInvoke.Core" Version="3.0.0" />
    <PackageVersion Include="CliInvoke" Version="3.0.0" />
    <PackageVersion Include="DotMake.CommandLine" Version="3.7.0" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageVersion Include="EnhancedLinq" Version="1.1.0" />
    <PackageVersion Include="NuGet.Protocol" Version="7.9.0" />
    <PackageVersion Include="Polyfill" PrivateAssets="all" Version="11.3.0" />
  </ItemGroup>
</Project>